CREATE TABLE series (
id INT PRIMARY KEY)
CREATE TABLE subgenres(id INT PRIMARY KEY)
CREATE TABLE authors(id INT PRIMARY KEY)
CREATE TABLE books(id INT PRIMARY KEY)
CREATE TABLE characters(id INT PRIMARY KEY)
CREATE TABLE books(id INT PRIMARY KEY)