CREATE TABLE series (
id INT PRIMARY KEY)
CREATE TABLE subgenre(id INT PRIMARY KEY)
CREATE TABLE (id INT PRIMARY KEY)
CREATE TABLE (id INT PRIMARY KEY)
CREATE TABLE (id INT PRIMARY KEY)
CREATE TABLE (id INT PRIMARY KEY)