CREATE TABLE series (
id INT PRIMARY KEY)
CREATE TABLE sub_genre(id INT PRIMARY KEY)
CREATE TABLE (id INT PRIMARY KEY)
CREATE TABLE (id INT PRIMARY KEY)
CREATE TABLE (id INT PRIMARY KEY)
CREATE TABLE (id INT PRIMARY KEY)